# Generated by Django 4.1.7 on 2023-02-18 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('weapon', models.CharField(choices=[('Sploosh-o-matic', 'ボールドマーカー'), ('Splattershot Jr.', 'わかばシューター')], max_length=128)),
                ('stage', models.CharField(choices=[('Scorch Gorge', 'ユノハナ大渓谷'), ('Eeltail Alley', 'ゴンズイ地区'), ('Hagglefish Market', 'ヤガラ市場'), ('Undertow Spillway', 'マテガイ放水路'), ('Mincemeat Metalworks', 'ナメロウ金属'), ('Mahi-Mahi Resort', 'マヒマヒリゾート&スパ'), ("Museum d'Alfonsino", 'キンメダイ美術館'), ('Hammerhead Bridge', 'マサバ海峡大橋'), ('Inkblot Art Academy', '海女美術大学'), ('Strugeon Shipyard', 'チョウザメ造船'), ('Mako Mart', 'ザトウマーケット'), ('Wahoo World', 'スメーシーワールド'), ('Flounder Heights', 'ヒラメが丘団地'), ('Brinewater Springs', 'クサヤ温泉')], max_length=128)),
                ('rule', models.CharField(choices=[('Turf War', 'ナワバリバトル'), ('Splat Zones', 'ガチエリア'), ('Tower Control', 'ガチヤグラ'), ('Rainmaker', 'ガチホコバトル'), ('Clam Blitz', 'ガチアサリ')], max_length=128)),
                ('xp', models.IntegerField(validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(4000)])),
                ('memory_num', models.CharField(max_length=15)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
