# Generated by Django 4.1.7 on 2023-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0011_alter_memory_comment_alter_memory_memory_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_num',
            field=models.SlugField(max_length=19),
        ),
    ]
