# Generated by Django 4.1.7 on 2023-02-21 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0012_alter_memory_memory_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_num',
            field=models.SlugField(max_length=19, verbose_name='バトルメモリーのコード'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='xp',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(900), django.core.validators.MaxValueValidator(4000)], verbose_name='xp'),
        ),
        migrations.CreateModel(
            name='Viewer_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_comment', models.TextField(verbose_name='視聴者コメント')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.memory')),
            ],
        ),
    ]
